name: On push tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # release作成に必要

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: check existing release
        run: |
          echo "Triggered by tag: ${{ github.ref_name }}"
          # 同名のreleaseがすでに存在する場合は処理中止にする. 同名releaseが新規に生成されるとややこしいため
          if gh release view "${{ github.ref_name }}" > /dev/null 2>&1; then \
            echo "Release for tag ${{ github.ref_name }} already exists. Exiting." \
            exit 1 \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build app
        run: |
          echo "build app ... done."
          echo "tag: ${{ github.ref_name }}" > tag.txt
      
      - name: create GitHub Release
        run: | # actions/create-release はメンテナンスされなくなったのでgh CLIを使用
          gh release create "${{ github.ref_name }}" \
          tag.txt \
          --title "${{ github.ref_name }}" \
          --notes "Release for tag ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

